my d3 AMD solution errors...trying again
SyntaxError: missing } after property list sankey.js:11
TypeError: d3.sankey is not a function navigator.html:164