added } to solve d3 error
SyntaxError: missing } after property list sankey.js:11
SyntaxError: missing } after property list sankey.js:11
TypeError: d3.sankey is not a function